apiVersion: v1
kind: ConfigMap
metadata:
  name: searchapiconfig
  namespace: {{.Values.namespace}}
data:
  ImageSettings__Url: "{{ .Values.imageServer }}"
  ElasticSettings__CloudId: "{{ .Values.cloudId }}"
  ElasticSettings__ApiKey: "{{ .Values.apikey }}"
  AllowedHosts: "{{ .Values.allowedHosts}}"