apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: search-api
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
        - name: search-api
          image: "{{ .Values.imagePath }}"
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: searchapisettings
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
              cpu: 250m
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
