apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
 name: searchserver
 namespace: {{.Values.namespace | quote}}
spec:
 hosts:
   - '*'
 gateways:
   - istio-ingress/root-gateway
 http:
 - match:
   - uri:
       prefix: /api/v1/search
   route:
   - destination:
       host: search-api-svc.amcart.svc.cluster.local
       port:
         number: 8080
 