apiVersion: v1
kind: Service
metadata:
  name: search-api-svc
  namespace: {{.Values.namespace | quote}}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: search-api
  type: LoadBalancer
